config/routes.rb
CerpenSite::Application.routes.draw do
  resources :chapters

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chapters }
    end
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chapter }
    end
  end

  # GET /chapters/new
  # GET /chapters/new.json
  def new
    @chapter = Chapter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chapter }
    end
  end

  # GET /chapters/1/edit
  def edit
    @chapter = Chapter.find(params[:id])
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(params[:chapter])

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render json: @chapter, status: :created, location: @chapter }
      else
        format.html { render action: "new" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chapters/1
  # PUT /chapters/1.json
  def update
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      if @chapter.update_attributes(params[:chapter])
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_for(@chapter) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<h1>Listing chapters</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chapters.each do |chapter| %>
  <tr>
    <td><%= chapter.title %></td>
    <td><%= chapter.content %></td>
    <td><%= link_to 'Show', chapter %></td>
    <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
    <td><%= link_to 'Destroy', chapter, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @chapter.title %>
</p>

<p>
  <b>Content:</b>
  <%= @chapter.content %>
</p>


<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CerpenSite</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>